<center><a href="#" onclick="addtext(':)'); return false"><img src="/mytcg/imgs/smile.png" alt=":)" /></a>
<a href="#" onclick="addtext(':('); return false"><img src="/mytcg/imgs/sad.png" alt=":(" /></a>
<a href="#" onclick="addtext(':x'); return false"><img src="/mytcg/imgs/kiss.png" alt=":x" /></a>
<a href="#" onclick="addtext(';)'); return false"><img src="/mytcg/imgs/wink.png" alt=";)" /></a>
<a href="#" onclick="addtext(':p'); return false"><img src="/mytcg/imgs/tongue.png" alt=":P" /></a>
<a href="#" onclick="addtext(':o'); return false"><img src="/mytcg/imgs/oh.png" alt=":o" /></a>
<a href="#" onclick="addtext(':heart:'); return false"><img src="/mytcg/imgs/heart.png" alt=":heart:" /></a>
<a href="#" onclick="addtext(':grin:'); return false"><img src="/mytcg/imgs/grin.png" alt=":grin:" /></a>
<a href="#" onclick="addtext(':angry:'); return false"><img src="/mytcg/imgs/angry.png" alt=":angry:" /></a>
<a href="#" onclick="addtext(':bad:'); return false"><img src="/mytcg/imgs/bad.png" alt=":bad:" /></a>
<a href="#" onclick="addtext(':blowkiss:'); return false"><img src="/mytcg/imgs/blowkiss.png" alt=":blowkiss:" /></a><br>
<a href="#" onclick="addtext(':bye:'); return false"><img src="/mytcg/imgs/bye.png" alt=":bye:" /></a>
<a href="#" onclick="addtext(':clap:'); return false"><img src="/mytcg/imgs/clap.png" alt=":clap:" /></a>
<a href="#" onclick="addtext(':confused:'); return false"><img src="/mytcg/imgs/confused.png" alt=":confused:" /></a>
<a href="#" onclick="addtext(':cute:'); return false"><img src="/mytcg/imgs/cute.png" alt=":cute:" /></a>
<a href="#" onclick="addtext(':desire:'); return false"><img src="/mytcg/imgs/desire.png" alt=":desire:" /></a>
<a href="#" onclick="addtext(':devil:'); return false"><img src="/mytcg/imgs/devil.png" alt=":devil:" /></a>
<a href="#" onclick="addtext(':giggle:'); return false"><img src="/mytcg/imgs/giggle.png" alt=":giggle:" /></a>
<a href="#" onclick="addtext(':ghost:'); return false"><img src="/mytcg/imgs/ghost.png" alt=":ghost:" /></a>
<a href="#" onclick="addtext(':laugh:'); return false"><img src="/mytcg/imgs/laugh.png" alt=":laugh:" /></a>
<a href="#" onclick="addtext('-_-'); return false"><img src="/mytcg/imgs/neutral.png" alt="-_-" /></a>
<a href="#" onclick="addtext(':question:'); return false"><img src="/mytcg/imgs/question.png" alt=":question:" /></a></center>